"""Ajout Matricule 

Revision ID: 11fe18551e72
Revises: 5af60c8d357e
Create Date: 2026-08-03 17:52:38.237634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11fe18551e72'
down_revision = '5af60c8d357e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matricule', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['matricule'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('matricule')

    # ### end Alembic commands ###
