"""Ajout de la colonne name a Rapport_de_compte

Revision ID: 187fcb70fa65
Revises: d021cd8a7282
Create Date: 2026-09-14 12:52:35.262762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '187fcb70fa65'
down_revision = 'd021cd8a7282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rapport_de_compte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rapport_de_compte', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
