"""ajout quantite et prix_unitaire a ligne_commande

Revision ID: 1c530fb28573
Revises: 84e4b1fe9e9e
Create Date: 2026-09-19 11:25:01.251328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c530fb28573'
down_revision = '84e4b1fe9e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ligne_commande', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantite', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('prix_unitaire', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ligne_commande', schema=None) as batch_op:
        batch_op.drop_column('prix_unitaire')
        batch_op.drop_column('quantite')

    # ### end Alembic commands ###
