"""Modification table client 

Revision ID: 59abd92eb022
Revises: 7d5fa5b83ccc
Create Date: 2026-08-03 13:01:36.424545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59abd92eb022'
down_revision = '7d5fa5b83ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('rôle')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('Gérant', 'Caissier', 'Serveur', 'Livreur', 'DAF'),
               type_=sa.Enum('GERANT', 'CAISSIER', 'SERVEUR', 'LIVREUR', 'DAF', name='roleenum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('GERANT', 'CAISSIER', 'SERVEUR', 'LIVREUR', 'DAF', name='roleenum'),
               type_=mysql.ENUM('Gérant', 'Caissier', 'Serveur', 'Livreur', 'DAF'),
               existing_nullable=False)

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rôle', mysql.ENUM('Gérant', 'Caissier', 'Serveur', 'Livreur', 'DAF'), nullable=False))

    # ### end Alembic commands ###
