"""ajout champ user

Revision ID: 7d5fa5b83ccc
Revises: 
Create Date: 2026-08-03 11:14:02.025191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d5fa5b83ccc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rôle', sa.Enum('Gérant', 'Caissier', 'Serveur', 'Livreur', 'DAF', name='role_enum'), nullable=False))

    with op.batch_alter_table('commande', schema=None) as batch_op:
        batch_op.drop_column('statut')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('telephone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('ville', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('quartier', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('mot_de_passe', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('role', sa.Enum('Gérant', 'Caissier', 'Serveur', 'Livreur', 'DAF', name='role_enum'), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('role')
        batch_op.drop_column('mot_de_passe')
        batch_op.drop_column('quartier')
        batch_op.drop_column('ville')
        batch_op.drop_column('telephone')
        batch_op.drop_column('email')

    with op.batch_alter_table('commande', schema=None) as batch_op:
        batch_op.add_column(sa.Column('statut', mysql.ENUM('en_attente', 'validee', 'annulee'), nullable=False))

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('rôle')

    # ### end Alembic commands ###
