"""Mise a jour colonnes dates Rapport_de_compte

Revision ID: 824ba4e97214
Revises: 187fcb70fa65
Create Date: 2026-09-18 15:04:35.962332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '824ba4e97214'
down_revision = '187fcb70fa65'
branch_labels = None
depends_on = None

def upgrade():
    with op.batch_alter_table('rapport_de_compte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_debut', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_fin', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rapport_de_compte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_generation', mysql.DATETIME(), nullable=False))
        batch_op.drop_column('date_fin')
        batch_op.drop_column('date_debut')

    # ### end Alembic commands ###
