"""Mise a jour colonnes dates Rapport_de_compte

Revision ID: 84e4b1fe9e9e
Revises: 824ba4e97214
Create Date: 2026-09-18 15:27:32.172796

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84e4b1fe9e9e'
down_revision = '824ba4e97214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rapport_de_compte', schema=None) as batch_op:
        batch_op.drop_column('date_generation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rapport_de_compte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_generation', mysql.DATETIME(), nullable=False))

    # ### end Alembic commands ###
