"""Ajout de la colonne status a Produits

Revision ID: a2f601f6ea88
Revises: 11fe18551e72
Create Date: 2026-09-04 14:37:07.270013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2f601f6ea88'
down_revision = '11fe18551e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('En stock', 'Épuisé', name='status_produit_enum'), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['matricule'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('produits', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
