"""ajout de la colonne email dans Client

Revision ID: bcdf2649326c
Revises: 1c530fb28573
Create Date: 2026-10-09 10:04:18.261360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bcdf2649326c'
down_revision = '1c530fb28573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vente_sauvegarde')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vente_sauvegarde',
    sa.Column('id_vente', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('id_commande', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('montant_percue', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('montant_attendu', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('statut', mysql.ENUM('payee', 'partielle', 'impayee'), nullable=False),
    sa.Column('mode_vente', mysql.ENUM('comptant', 'credit', 'livraison'), nullable=False),
    sa.Column('id_utilisateur', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('date_vente', mysql.DATETIME(), nullable=False),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
