"""Ajout de la colonne name a Rapport_de_compte

Revision ID: d021cd8a7282
Revises: a2f601f6ea88
Create Date: 2026-09-14 12:29:18.861124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd021cd8a7282'
down_revision = 'a2f601f6ea88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rapport_de_compte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rapport_de_compte', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
